### ISSUE TITLE
ImportError: cannot import name '_PosixFlavor' from 'pathlib' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py)

### ISSUE THREAD

**Issue by EReaso** [top-on/offline-docs#1]
Hello! It looks like there's a bug causing this error. Maybe there's a public class that works?

I'm on MacOS 15.4 with Python 3.12.3. 

When I'm able, I might open a PR with a fix.

**Comment by EReaso** [comment]
It seems the issue is in the URLPath library. I'm keeping this open for now.

**Comment by EReaso** [comment]
Works on 3.11
